template_path: templates/code-pipeline.yaml

parameters:
    SiteBucketName: !stack_output s3-sites::SiteBucketName
    GitHubUser: rikbrown
    GitHubRepo: hastrumpfiredmuelleryet.com
    GitHubToken: {{ environment_variable.GITHUB_TOKEN }}
